name: Test for CI, S3 cp for CD

on: [push]

jobs:
  test:

    runs-on: ubuntu-20.04
    env:
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      LINE_CLIENT_SECRET: ${{ secrets.LINE_CLIENT_SECRET }}
      LINE_CLIENT_ID: ${{ secrets.LINE_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --debug

  s3_cp_for_aws_codepipeline:
    needs: test
    if: github.ref == 'refs/heads/production'

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - run: git archive -o build.zip HEAD
    - run: aws s3 cp ./build.zip s3://gongbu-app-pipeline-src/build.zip